
title: Justin's Resume
url: 'http://justinpobrien.com'
baseurl: '/justinpobrien.github.io' #change it according to your repository name


# Enable one of these styles by removing #
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Justin O'Brien
tagline: Product Manager
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: justin@justinpobrien.com
phone: 408-438-3755
website: justinpobrien.com #do not add http://
linkedin: justinpobrien
github: justinpobrien
twitter: '@justinpobrien'
